---
title: "Flow maps"
author: "Diego Villa"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(dplyr)
library(sf)
library(ggplot2)
library(stplanr)
library(readr)
library(ggraph)
library(tidygraph)
```


```{r}
edges_raw <- read_csv("data/processed/actual-edges.csv", col_types = "cccd")
```

```{r}
nodes_raw <- read_csv("data/processed/nodes.csv", col_types = "ccccdccccd")
```


```{r}
villages_raw <- st_read("data/raw/ccpp-original.gpkg")
```

```{r}
ana_hydro <- st_read("data/raw/ana-hydrobasin.gpkg")
```

```{r}
edges <- edges_raw %>% 
  group_by(hydro_name_ana) %>% 
  # mutate(across(where(is.numeric), ~ .x / mean(.x))) %>% 
  mutate(across(where(is.numeric), ~ scales::rescale(.x))) %>% 
  ungroup() %>% 
  select(from, to, everything())
```

```{r}
nodes <- nodes_raw %>% 
  select(village_id = ccpp_id, hydro_name_ana)
```

```{r}
villages <- villages_raw %>%
  select(village_id = id_loc, village_name = village, population = nrohab) %>% 
  filter(village_id %in% c(edges$from, edges$to)) %>% 
  left_join(nodes, by = "village_id")
```

```{r}
od_lines <- od2line(edges, villages)
```

```{r}
od_lines_test <- od_lines %>% 
  filter(t_inv == 1)
```


```{r}
flow_map <- ggplot() +
  geom_sf(data = ana_hydro, fill = NA) +
  geom_sf(data = od_lines, aes(alpha = t_inv, col = hydro_name_ana), lwd = 0.05) +
  geom_sf(data = villages, aes(col = hydro_name_ana), size = 0.05) +
  theme_minimal() +
  theme(legend.position="none")
```

```{r}
ggsave("figs/plot.pdf", device = "pdf", dpi = 300)
```

