---
title: "Exploratory data analysis"
author: "Diego Villa"
date: "`r Sys.Date()`"
output: html_document
---

```{r message=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(geofacet)
library(ggsci)
library(ggplot2)
```

```{r}
malaria_raw <- read_csv(
  "data/raw/malaria-cases.csv",
  col_select = c(
    province, district, village, village_id = id_loc, population = nrohab,
    year, month, falciparum = fal, vivax = viv, river_name = RiverName, 
    hydro_name_ana = HydroNameANA, hydro_name_l6 = HydroNameL6, 
    hydro_name_l7 = HydroNameL7
  )
)
```

```{r}
nodes <- read_csv("data/processed/nodes.csv", col_types = "ccccdccccd")
```

```{r}
watersheds <- unique(nodes$hydro_name_ana)
```

```{r}
malaria <- malaria_raw %>% 
  filter(hydro_name_ana %in% watersheds)
```

```{r message=FALSE}
air_malaria <- malaria %>% 
  group_by(hydro_name_ana, year, month) %>% 
  summarise(
    vivax = sum(vivax), falciparum = sum(falciparum), population = sum(population)
  ) %>% 
  mutate(ir_vivax = vivax / population, ir_falciparum = falciparum / population) %>% 
  group_by(hydro_name_ana, year) %>% 
  summarise(
    air_vivax = mean(ir_vivax), air_falciparum = mean(ir_falciparum), 
    .groups = "drop"
  )
```

```{r}
air_malaria_long <- air_malaria %>% 
  pivot_longer(
    c(air_vivax, air_falciparum), names_to = "specie", names_prefix = "air_", 
    values_to = "air"
  ) %>% 
  mutate(
    specie = factor(
      specie, levels = c("vivax", "falciparum"), 
      labels = c("P. vivax", "P. falciparum")
    )
  ) %>% 
  filter(between(year, 2011, 2018))
```


```{r fig.height=18, fig.width=18}
# hydro_grid <- data.frame(
#   code = c("Cuenca Napo", "Cuenca Putumayo", "Cuenca Tigre", "Cuenca Morona", "Intercuenca 49793", "Cuenca Nanay", "Intercuenca 4977", "Cuenca Itaya", "Cuenca Pastaza", "Intercuenca 49873", "Intercuenca 49795", "Intercuenca 49791", "Intercuenca 49799", "Intercuenca Medio Bajo Marañón", "Intercuenca Medio Marañón", "Intercuenca 49877", "Intercuenca 49871", "Intercuenca 49797", "Cuenca Manití", "Cuenca Tahuayo", "Intercuenca Bajo Marañón", "Intercuenca Bajo Huallaga", "Cuenca Potro", "Cuenca Carhuapanas", "Cuenca Yavari", "Intercuenca 49911", "Cuenca Tapiche", "Intercuenca Medio Bajo Huallaga", "Cuenca Paranapura", "Intercuenca 49913", "Intercuenca 49915"),
#   name = c("C Napo", "C Putumayo", "C Tigre", "C Morona", "IC 49793", "C Nanay", "IC 4977", "C Itaya", "C Pastaza", "IC 49873", "IC 49795", "IC 49791", "IC 49799", "IC Medio Bajo Marañón", "IC Medio Marañón", "IC 49877", "IC 49871", "IC 49797", "C Manití", "C Tahuayo", "IC Bajo Marañón", "IC Bajo Huallaga", "C Potro", "C Carhuapanas", "C Yavari", "IC 49911", "C Tapiche", "IC Medio Bajo Huallaga", "C Paranapura", "IC 49913", "IC 49915"),
#   row = c(3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 9) - 2,
#   col = c(9, 10, 8, 6, 10, 9, 11, 8, 7, 5, 9, 10, 8, 7, 6, 4, 5, 9, 10, 8, 7, 6, 4, 5, 9, 8, 7, 6, 5, 6, 6) - 3,
#   stringsAsFactors = FALSE
# )
```

```{r}
# Grid data (csv) for Geo Grid Designer
# code,name,row,col
# Cuenca Putumayo,C Putumayo,1,6
# Cuenca Tigre,C Tigre,2,5
# Cuenca Napo,C Napo,2,6
# Intercuenca 49793,IC 49793,2,7
# Cuenca Morona,C Morona,3,4
# Cuenca Itaya,C Itaya,3,5
# Cuenca Nanay,C Nanay,3,6
# Intercuenca 4977,IC 4977,3,8
# Intercuenca 49795,IC 49795,3,7
# Intercuenca Medio Marañón,IC Medio Marañón,4,3
# Cuenca Pastaza,C Pastaza,4,4
# Intercuenca 49799,IC 49799,4,6
# Intercuenca 49791,IC 49791,4,9
# Intercuenca 49797,IC 49797,4,8
# Cuenca Tahuayo,C Tahuayo,4,7
# Intercuenca Bajo Marañón,IC Bajo Marañón,4,5
# Intercuenca 49873,IC 49873,5,3
# Intercuenca Medio Bajo Marañón,IC Medio Bajo Marañón,5,4
# Cuenca Manití,C Manití,5,8
# Intercuenca 49911,IC 49911,5,7
# Cuenca Tapiche,C Tapiche,5,6
# Intercuenca Medio Bajo Huallaga,IC Medio Bajo Huallaga,5,5
# Intercuenca 49871,IC 49871,5,2
# Intercuenca Bajo Huallaga,IC Bajo Huallaga,6,3
# Cuenca Carhuapanas,C Carhuapanas,6,4
# Cuenca Yavari,C Yavari,6,7
# Intercuenca 49913,IC 49913,6,6
# Intercuenca 49915,IC 49915,6,5
# Intercuenca 49877,IC 49877,6,2
# Cuenca Potro,C Potro,7,3
# Cuenca Paranapura,C Paranapura,7,4
```

```{r}
# hydro_grid <- data.frame(
#   code = c("Cuenca Putumayo", "Cuenca Tigre", "Cuenca Napo", "Intercuenca 49793", "Cuenca Morona", "Cuenca Itaya", "Cuenca Nanay", "Intercuenca 4977", "Intercuenca 49795", "Intercuenca Medio Marañón", "Cuenca Pastaza", "Intercuenca 49799", "Intercuenca 49791", "Intercuenca 49797", "Cuenca Tahuayo", "Intercuenca Bajo Marañón", "Intercuenca 49873", "Intercuenca Medio Bajo Marañón", "Cuenca Manití", "Intercuenca 49911", "Cuenca Tapiche", "Intercuenca Medio Bajo Huallaga", "Intercuenca 49871", "Intercuenca Bajo Huallaga", "Cuenca Carhuapanas", "Cuenca Yavari", "Intercuenca 49913", "Intercuenca 49915", "Intercuenca 49877", "Cuenca Potro", "Cuenca Paranapura"),
#   name = c("C Putumayo", "C Tigre", "C Napo", "IC 49793", "C Morona", "C Itaya", "C Nanay", "IC 4977", "IC 49795", "IC Medio Marañón", "C Pastaza", "IC 49799", "IC 49791", "IC 49797", "C Tahuayo", "IC Bajo Marañón", "IC 49873", "IC Medio Bajo Marañón", "C Manití", "IC 49911", "C Tapiche", "IC Medio Bajo Huallaga", "IC 49871", "IC Bajo Huallaga", "C Carhuapanas", "C Yavari", "IC 49913", "IC 49915", "IC 49877", "C Potro", "C Paranapura"),
#   row = c(1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7),
#   col = c(6, 5, 6, 7, 4, 5, 6, 8, 7, 3, 4, 6, 9, 8, 7, 5, 3, 4, 8, 7, 6, 5, 2, 3, 4, 7, 6, 5, 2, 3, 4),
#   stringsAsFactors = FALSE
# )
```

```{r}
hydro_grid <- data.frame(
  code = c("Cuenca Putumayo", "Cuenca Itaya", "Cuenca Napo", "Cuenca Tigre", "Cuenca Morona", "Intercuenca 49799", "Cuenca Nanay", "Intercuenca 49793", "Cuenca Pastaza", "Intercuenca Medio Marañón", "Intercuenca 49873", "Intercuenca 49877", "Cuenca Tahuayo", "Intercuenca 49795", "Intercuenca 49791", "Intercuenca 4977", "Intercuenca Medio Bajo Marañón", "Intercuenca Bajo Huallaga", "Intercuenca 49871", "Intercuenca 49911", "Cuenca Yavari", "Cuenca Manití", "Intercuenca Bajo Marañón", "Intercuenca Medio Bajo Huallaga", "Cuenca Carhuapanas", "Cuenca Potro", "Intercuenca 49797", "Cuenca Tapiche", "Intercuenca 49913", "Cuenca Paranapura", "Intercuenca 49915"),
  name = c("C Putumayo", "C Itaya", "C Napo", "C Tigre", "C Morona", "IC 49799", "C Nanay", "IC 49793", "C Pastaza", "IC Medio Marañón", "IC 49873", "IC 49877", "C Tahuayo", "IC 49795", "IC 49791", "IC 4977", "IC Medio Bajo Marañón", "IC Bajo Huallaga", "IC 49871", "IC 49911", "C Yavari", "C Manití", "IC Bajo Marañón", "IC Medio Bajo Huallaga", "C Carhuapanas", "C Potro", "IC 49797", "C Tapiche", "IC 49913", "C Paranapura", "IC 49915"),
  row = c(1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 4, 6, 6, 6, 6, 7),
  col = c(5, 5, 6, 4, 3, 5, 6, 7, 4, 3, 2, 1, 5, 6, 7, 8, 4, 3, 2, 5, 6, 7, 4, 3, 2, 1, 5, 4, 3, 2, 3),
  stringsAsFactors = FALSE
)
```


```{r fig.height=15, fig.width=20, message=FALSE}
plot_air_hydro <- 
  air_malaria_long %>% 
  ggplot() +
  facet_geo(~ hydro_name_ana, grid = hydro_grid, label = "name") +
  geom_area(
    aes(year, y = 1000 * air, color = specie, fill = specie),
    size = 1, alpha = 0.3, position = position_dodge(0)
  ) +
  # scale_y_continuous(limits = c(0, 150)) +
  scale_x_continuous(n.breaks = 5) +
  scale_color_npg() +
  scale_fill_npg() +
  labs(y = "Annual incidence rate", x = NULL) +
  theme_bw() +
  theme(
    legend.position = "top", legend.title = element_blank(), 
    text = element_text(size = 18)
  )

plot_air_hydro
```

```{r}
ggsave(
  "figs/air-hydro-facet.png", plot = plot_air_hydro, 
  height = 15, width = 24, units = "in"
)
```






